USE `blog`;

ALTER TABLE `posts`
  ADD COLUMN IF NOT EXISTS `series` VARCHAR(120) NULL DEFAULT NULL COMMENT '系列名' AFTER `cover`,
  ADD COLUMN IF NOT EXISTS `series_order` INT NOT NULL DEFAULT 0 COMMENT '系列内序号' AFTER `series`;
